/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CyberpunkRouteRouteImport } from './routes/cyberpunk/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CyberpunkIndexRouteImport } from './routes/cyberpunk/index'
import { Route as CyberpunkContactIndexRouteImport } from './routes/cyberpunk/contact/index'
import { Route as CyberpunkProjectsSlugRouteImport } from './routes/cyberpunk/projects/$slug'

const CyberpunkRouteRoute = CyberpunkRouteRouteImport.update({
  id: '/cyberpunk',
  path: '/cyberpunk',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CyberpunkIndexRoute = CyberpunkIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CyberpunkRouteRoute,
} as any)
const CyberpunkContactIndexRoute = CyberpunkContactIndexRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => CyberpunkRouteRoute,
} as any)
const CyberpunkProjectsSlugRoute = CyberpunkProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => CyberpunkRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cyberpunk': typeof CyberpunkRouteRouteWithChildren
  '/cyberpunk/': typeof CyberpunkIndexRoute
  '/cyberpunk/projects/$slug': typeof CyberpunkProjectsSlugRoute
  '/cyberpunk/contact/': typeof CyberpunkContactIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cyberpunk': typeof CyberpunkIndexRoute
  '/cyberpunk/projects/$slug': typeof CyberpunkProjectsSlugRoute
  '/cyberpunk/contact': typeof CyberpunkContactIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cyberpunk': typeof CyberpunkRouteRouteWithChildren
  '/cyberpunk/': typeof CyberpunkIndexRoute
  '/cyberpunk/projects/$slug': typeof CyberpunkProjectsSlugRoute
  '/cyberpunk/contact/': typeof CyberpunkContactIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cyberpunk'
    | '/cyberpunk/'
    | '/cyberpunk/projects/$slug'
    | '/cyberpunk/contact/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cyberpunk' | '/cyberpunk/projects/$slug' | '/cyberpunk/contact'
  id:
    | '__root__'
    | '/'
    | '/cyberpunk'
    | '/cyberpunk/'
    | '/cyberpunk/projects/$slug'
    | '/cyberpunk/contact/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CyberpunkRouteRoute: typeof CyberpunkRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/cyberpunk': {
      id: '/cyberpunk'
      path: '/cyberpunk'
      fullPath: '/cyberpunk'
      preLoaderRoute: typeof CyberpunkRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cyberpunk/': {
      id: '/cyberpunk/'
      path: '/'
      fullPath: '/cyberpunk/'
      preLoaderRoute: typeof CyberpunkIndexRouteImport
      parentRoute: typeof CyberpunkRouteRoute
    }
    '/cyberpunk/contact/': {
      id: '/cyberpunk/contact/'
      path: '/contact'
      fullPath: '/cyberpunk/contact/'
      preLoaderRoute: typeof CyberpunkContactIndexRouteImport
      parentRoute: typeof CyberpunkRouteRoute
    }
    '/cyberpunk/projects/$slug': {
      id: '/cyberpunk/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/cyberpunk/projects/$slug'
      preLoaderRoute: typeof CyberpunkProjectsSlugRouteImport
      parentRoute: typeof CyberpunkRouteRoute
    }
  }
}

interface CyberpunkRouteRouteChildren {
  CyberpunkIndexRoute: typeof CyberpunkIndexRoute
  CyberpunkProjectsSlugRoute: typeof CyberpunkProjectsSlugRoute
  CyberpunkContactIndexRoute: typeof CyberpunkContactIndexRoute
}

const CyberpunkRouteRouteChildren: CyberpunkRouteRouteChildren = {
  CyberpunkIndexRoute: CyberpunkIndexRoute,
  CyberpunkProjectsSlugRoute: CyberpunkProjectsSlugRoute,
  CyberpunkContactIndexRoute: CyberpunkContactIndexRoute,
}

const CyberpunkRouteRouteWithChildren = CyberpunkRouteRoute._addFileChildren(
  CyberpunkRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CyberpunkRouteRoute: CyberpunkRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
